version: '3.9'
services:
  mongodb:
    image: mongo:5.0.8
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  notion-api-cache:
    build: ../
    ports:
      - 8080:8080
    env_file:
      - ../.env