version: "3.9"
services:
  mongodb:
    image: mongo:6.0.4
    ports:
      - 27017:27017
    volumes:
      - ~/mongodb/notion-api-cache:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  notion-api-cache:
    build: ../
    ports:
      - 8080:8080
    env_file:
      - ../.env
